#!/bin/sh
#
# pmakempx - set default environment variables suitable for jMetaPost and
#            invoke makempx.
#
# $Id: pmakempx,v 1.3 1999/11/10 03:57:35 hideyuki Exp $

: ${DVITOMP=pdvitomp}
: ${TEX=ptex}

export DVITOMP
export TEX

exec makempx "$@"
